version: '3.7'
services:
  eureka-server:
    image: murilloalcantara/server:latest
    networks:
      - ms-network
    ports:
      - "8080:8080"
    environment:
      eureka.instance.hostname: eureka-server
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8080/eureka/
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbit
    restart: always
    networks:
      - ms-network
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./dados:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=murillo
      - RABBITMQ_DEFAULT_PASS=m123
networks:
  ms-network:
    driver: bridge